# Generated by Django 4.2.29 on 2026-03-20 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('place_type', models.CharField(choices=[('mart', '대형 마트'), ('gas_station', '주유소'), ('hotel', '호텔/모텔'), ('public', '공공기관'), ('etc', '기타')], default='etc', max_length=20)),
                ('charger_count', models.PositiveSmallIntegerField(default=1)),
                ('power_kw', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('open_hours', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('source_api_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '충전소',
                'verbose_name_plural': '충전소 목록',
            },
        ),
        migrations.CreateModel(
            name='Highway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('total_distance_km', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '고속도로',
                'verbose_name_plural': '고속도로 목록',
            },
        ),
        migrations.CreateModel(
            name='HighwayNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('IC', 'IC (나들목)'), ('RA', 'RA (휴게소)')], max_length=2)),
                ('direction', models.CharField(choices=[('UP', '상행'), ('DOWN', '하행')], max_length=4)),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_from_start_km', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='chargeflow.highway')),
            ],
            options={
                'verbose_name': '고속도로 노드',
                'verbose_name_plural': '고속도로 노드 목록',
                'ordering': ['highway', 'direction', 'sequence'],
                'unique_together': {('highway', 'direction', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='StationCongestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_count_30m', models.PositiveSmallIntegerField(default=0)),
                ('level', models.CharField(choices=[('smooth', '원활'), ('normal', '보통'), ('busy', '혼잡'), ('jammed', '매우 혼잡')], default='smooth', max_length=10)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ra_node', models.OneToOneField(limit_choices_to={'node_type': 'RA'}, on_delete=django.db.models.deletion.CASCADE, related_name='congestion', to='chargeflow.highwaynode')),
            ],
            options={
                'verbose_name': '휴게소 혼잡도',
                'verbose_name_plural': '휴게소 혼잡도 목록',
            },
        ),
        migrations.CreateModel(
            name='NodeStationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('drive_minutes', models.PositiveSmallIntegerField()),
                ('route_memo', models.TextField(blank=True)),
                ('is_recommended', models.BooleanField(default=True)),
                ('ic_node', models.ForeignKey(limit_choices_to={'node_type': 'IC'}, on_delete=django.db.models.deletion.CASCADE, related_name='nearby_stations', to='chargeflow.highwaynode')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ic_mappings', to='chargeflow.chargingstation')),
            ],
            options={
                'verbose_name': 'IC-충전소 매핑',
                'verbose_name_plural': 'IC-충전소 매핑 목록',
                'ordering': ['drive_minutes', 'distance_km'],
                'unique_together': {('ic_node', 'station')},
            },
        ),
        migrations.CreateModel(
            name='HighwayNodeCharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_id', models.CharField(max_length=20)),
                ('stat_name', models.CharField(max_length=100)),
                ('charger_cnt', models.PositiveSmallIntegerField(default=0)),
                ('ra_node', models.ForeignKey(limit_choices_to={'node_type': 'RA'}, on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='chargeflow.highwaynode')),
            ],
            options={
                'verbose_name': '휴게소 충전기 매핑',
                'verbose_name_plural': '휴게소 충전기 매핑 목록',
                'unique_together': {('ra_node', 'stat_id')},
            },
        ),
        migrations.CreateModel(
            name='ChargerStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_id', models.CharField(max_length=10)),
                ('stat', models.CharField(choices=[('1', '통신이상'), ('2', '충전가능'), ('3', '충전중'), ('4', '운영중지'), ('5', '점검중'), ('9', '상태미확인')], max_length=1)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('ra_node', models.ForeignKey(limit_choices_to={'node_type': 'RA'}, on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='chargeflow.highwaynode')),
            ],
            options={
                'verbose_name': '충전기 상태 이력',
                'verbose_name_plural': '충전기 상태 이력 목록',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['ra_node', 'checked_at'], name='chargeflow__ra_node_40f26d_idx')],
            },
        ),
    ]
