# Generated by Django 4.2.29 on 2026-03-19 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('place_type', models.CharField(choices=[('mart', '대형 마트'), ('gas_station', '주유소'), ('hotel', '호텔/모텔'), ('public', '공공기관'), ('etc', '기타')], default='etc', max_length=20)),
                ('charger_count', models.PositiveSmallIntegerField(default=1)),
                ('power_kw', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('open_hours', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('source_api_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '충전소',
                'verbose_name_plural': '충전소 목록',
            },
        ),
        migrations.CreateModel(
            name='Highway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('total_distance_km', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '고속도로',
                'verbose_name_plural': '고속도로 목록',
            },
        ),
        migrations.CreateModel(
            name='HighwayNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('IC', 'IC (나들목)'), ('RA', 'RA (휴게소)')], max_length=2)),
                ('direction', models.CharField(choices=[('UP', '상행'), ('DOWN', '하행')], max_length=4)),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_from_start_km', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('highway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='chargeflow.highway')),
            ],
            options={
                'verbose_name': '고속도로 노드',
                'verbose_name_plural': '고속도로 노드 목록',
                'ordering': ['highway', 'direction', 'sequence'],
                'unique_together': {('highway', 'direction', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='NodeStationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('drive_minutes', models.PositiveSmallIntegerField()),
                ('route_memo', models.TextField(blank=True)),
                ('is_recommended', models.BooleanField(default=True)),
                ('ic_node', models.ForeignKey(limit_choices_to={'node_type': 'IC'}, on_delete=django.db.models.deletion.CASCADE, related_name='nearby_stations', to='chargeflow.highwaynode')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ic_mappings', to='chargeflow.chargingstation')),
            ],
            options={
                'verbose_name': 'IC-충전소 매핑',
                'verbose_name_plural': 'IC-충전소 매핑 목록',
                'ordering': ['drive_minutes', 'distance_km'],
                'unique_together': {('ic_node', 'station')},
            },
        ),
    ]
