# Generated by Django 4.2.29 on 2026-03-19 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargeflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationCongestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_count_30m', models.PositiveSmallIntegerField(default=0)),
                ('level', models.CharField(choices=[('smooth', '원활'), ('normal', '보통'), ('busy', '혼잡'), ('jammed', '매우 혼잡')], default='smooth', max_length=10)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='congestion', to='chargeflow.chargingstation')),
            ],
            options={
                'verbose_name': '충전소 혼잡도',
                'verbose_name_plural': '충전소 혼잡도 목록',
            },
        ),
        migrations.CreateModel(
            name='ChargerStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_id', models.CharField(max_length=10)),
                ('stat', models.CharField(choices=[('1', '통신이상'), ('2', '충전가능'), ('3', '충전중'), ('4', '운영중지'), ('5', '점검중'), ('9', '상태미확인')], max_length=1)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='chargeflow.chargingstation')),
            ],
            options={
                'verbose_name': '충전기 상태 이력',
                'verbose_name_plural': '충전기 상태 이력 목록',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['station', 'checked_at'], name='chargeflow__station_723491_idx')],
            },
        ),
    ]
