# Generated by Django 4.2.29 on 2026-03-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargeflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highwaynode',
            name='next_ic',
            field=models.ForeignKey(blank=True, limit_choices_to={'node_type': 'IC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_for_ra', to='chargeflow.highwaynode'),
        ),
        migrations.AddField(
            model_name='highwaynode',
            name='prev_ic',
            field=models.ForeignKey(blank=True, limit_choices_to={'node_type': 'IC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_for_ra', to='chargeflow.highwaynode'),
        ),
    ]
