# Generated by Django 4.2.29 on 2026-03-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargeflow', '0002_highwaynode_next_ic_highwaynode_prev_ic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='kakao_place_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
