# Generated by Django 4.2.29 on 2026-08-20 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargeflow', '0003_chargingstation_kakao_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='connector_type',
            field=models.CharField(blank=True, choices=[('dc_combo', 'DC콤보'), ('ac3', 'AC3상'), ('dc_chademo', 'DC차데모'), ('dc_ac_combo', 'DC콤보+AC3상 겸용')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(db_index=True, max_length=64)),
                ('is_favorite', models.BooleanField(default=False)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ra_node', models.ForeignKey(limit_choices_to={'node_type': 'RA'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_routes', to='chargeflow.highwaynode')),
            ],
            options={
                'verbose_name': '사용자 최근/즐겨찾기 경로',
                'verbose_name_plural': '사용자 최근/즐겨찾기 경로 목록',
                'ordering': ['-last_used_at'],
                'unique_together': {('user_key', 'ra_node')},
            },
        ),
        migrations.CreateModel(
            name='CongestionNotifySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('ra_node', models.ForeignKey(limit_choices_to={'node_type': 'RA'}, on_delete=django.db.models.deletion.CASCADE, related_name='notify_subscriptions', to='chargeflow.highwaynode')),
            ],
            options={
                'verbose_name': '혼잡 해소 알림 구독',
                'verbose_name_plural': '혼잡 해소 알림 구독 목록',
                'unique_together': {('user_key', 'ra_node')},
            },
        ),
    ]
