# Generated by Django 4.2.29 on 2026-10-03 11:01

from django.db import migrations, models
import django.utils.timezone


def reset_derived_data(apps, schema_editor):
    # 기존 폴러는 statId 필터가 없는 API를 휴게소별로 호출해 다른 충전기 상태를
    # 기록했으므로, 이력과 혼잡도 집계는 신뢰할 수 없다. 새 폴러가 다시 채운다.
    apps.get_model('chargeflow', 'ChargerStatusLog').objects.all().delete()
    apps.get_model('chargeflow', 'StationCongestion').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chargeflow', '0004_chargingstation_connector_type_userroute_and_more'),
    ]

    operations = [
        migrations.RunPython(reset_derived_data, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ChargerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_id', models.CharField(max_length=20)),
                ('charger_id', models.CharField(max_length=10)),
                ('stat', models.CharField(choices=[('1', '통신이상'), ('2', '충전가능'), ('3', '충전중'), ('4', '운영중지'), ('5', '점검중'), ('9', '상태미확인')], max_length=1)),
                ('stat_updated_at', models.DateTimeField(blank=True, null=True)),
                ('zcode', models.CharField(blank=True, max_length=2)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '충전기 최신 상태',
                'verbose_name_plural': '충전기 최신 상태 목록',
            },
        ),
        migrations.CreateModel(
            name='PollerStatus',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_status_at', models.DateTimeField(blank=True, null=True)),
                ('last_baseline_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '폴링 상태',
                'verbose_name_plural': '폴링 상태',
            },
        ),
        migrations.RemoveIndex(
            model_name='chargerstatuslog',
            name='chargeflow__ra_node_40f26d_idx',
        ),
        migrations.RemoveField(
            model_name='chargerstatuslog',
            name='ra_node',
        ),
        migrations.RemoveField(
            model_name='stationcongestion',
            name='is_suspicious',
        ),
        migrations.AddField(
            model_name='chargerstatuslog',
            name='stat_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='congestionnotifysubscription',
            name='subscribed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stationcongestion',
            name='available',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stationcongestion',
            name='charging',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stationcongestion',
            name='offline',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stationcongestion',
            name='total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stationcongestion',
            name='level',
            field=models.CharField(choices=[('smooth', '여유'), ('normal', '보통'), ('busy', '혼잡'), ('jammed', '만석'), ('unavailable', '이용 불가'), ('unknown', '정보 없음')], default='unknown', max_length=12),
        ),
        migrations.AddIndex(
            model_name='chargerstatuslog',
            index=models.Index(fields=['stat_id', 'checked_at'], name='chargeflow__stat_id_0530be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chargerstate',
            unique_together={('stat_id', 'charger_id')},
        ),
    ]
