# Generated by Django 4.2.29 on 2026-10-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargeflow', '0005_realtime_charger_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congestionnotifysubscription',
            name='user_key',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='userroute',
            name='user_key',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
