# Generated by Django 4.2.29 on 2026-10-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargeflow', '0006_widen_user_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=128, unique=True)),
                ('connector', models.CharField(blank=True, choices=[('', '전체'), ('combo', 'DC콤보'), ('chademo', 'DC차데모'), ('ac3', 'AC3상'), ('nacs', 'NACS(테슬라)')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사용자 설정',
                'verbose_name_plural': '사용자 설정 목록',
            },
        ),
        migrations.AddField(
            model_name='chargerstate',
            name='charging_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargerstate',
            name='chger_type',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='connectors',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='highway',
            name='down_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='highway',
            name='end_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='highway',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='highway',
            name='start_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='highway',
            name='up_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='nodestationmapping',
            name='is_estimated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userroute',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userroute',
            name='notify_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CongestionSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('samples', models.PositiveIntegerField(default=0)),
                ('waiting_samples', models.PositiveIntegerField(default=0)),
                ('available_sum', models.FloatField(default=0)),
                ('ra_node', models.ForeignKey(limit_choices_to={'node_type': 'RA'}, on_delete=django.db.models.deletion.CASCADE, related_name='congestion_samples', to='chargeflow.highwaynode')),
            ],
            options={
                'verbose_name': '혼잡 패턴 표본',
                'verbose_name_plural': '혼잡 패턴 표본 목록',
                'unique_together': {('ra_node', 'weekday', 'hour')},
            },
        ),
    ]
